2018-03-27 20:24:40.421 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-27 20:25:12.577 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:25:33.292 [error] <0.177.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.182.0> exit with reason normal in context child_terminated
2018-03-27 20:25:52.007 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:28:59.387 [error] <0.210.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.215.0> exit with reason normal in context child_terminated
2018-03-27 20:28:59.555 [error] <0.281.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.281.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:28:59.556 [error] <0.278.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.278.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8408>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.280.0>, {<<"client 127.0.0.1:60444 -> 127.0.0.1:5672">>,1}) at <0.281.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:28:59.556 [error] <0.278.0> Supervisor {<0.278.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8408>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.280.0>, {<<"client 127.0.0.1:60444 -> 127.0.0.1:5672">>,1}) at <0.281.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:28:59.556 [error] <0.265.0> Supervisor {<0.265.0>,'Elixir.Backbone.Supervisor'} had child 'Elixir.Backbone.Consumer' started with 'Elixir.Backbone.Consumer':start_link([], [{name,'Elixir.Backbone.Consumer'}]) at undefined exit with reason {shutdown,{gen_server,call,[<0.280.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.266.0>},60000]}} in context start_error
2018-03-27 20:35:56.229 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:35:56.414 [error] <0.243.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.243.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:35:56.415 [error] <0.240.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:60975 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:35:56.415 [error] <0.240.0> Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:60975 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:35:56.415 [error] <0.227.0> Supervisor {<0.227.0>,'Elixir.Backbone.Supervisor'} had child 'Elixir.Backbone.Consumer' started with 'Elixir.Backbone.Consumer':start_link([], [{name,'Elixir.Backbone.Consumer'}]) at undefined exit with reason {shutdown,{gen_server,call,[<0.242.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.228.0>},60000]}} in context start_error
2018-03-27 20:35:56.415 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Backbone.Consumer',{shutdown,{gen_server,call,[<0.242.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.228.0>},60000]}}}},{'Elixir.Backbone.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-27 20:36:30.356 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:36:30.543 [error] <0.243.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.243.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:36:30.544 [error] <0.240.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61003 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:36:30.544 [error] <0.240.0> Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61003 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:36:43.478 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:36:43.641 [error] <0.243.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.243.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:36:43.642 [error] <0.240.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61015 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:36:43.642 [error] <0.240.0> Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61015 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:36:58.996 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:36:59.143 [error] <0.243.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.243.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:36:59.143 [error] <0.240.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61030 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:36:59.143 [error] <0.240.0> Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61030 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:36:59.144 [error] <0.227.0> Supervisor {<0.227.0>,'Elixir.Backbone.Supervisor'} had child 'Elixir.Backbone.Consumer' started with 'Elixir.Backbone.Consumer':start_link([], [{name,'Elixir.Backbone.Consumer'}]) at undefined exit with reason {shutdown,{gen_server,call,[<0.242.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.228.0>},60000]}} in context start_error
2018-03-27 20:36:59.144 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Backbone.Consumer',{shutdown,{gen_server,call,[<0.242.0>,{call,{'queue.declare',0,nil,false,true,false,false,false,[]},none,<0.228.0>},60000]}}}},{'Elixir.Backbone.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-27 20:37:38.757 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:37:38.999 [error] <0.243.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 CRASH REPORT Process <0.243.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
2018-03-27 20:37:38.999 [error] <0.240.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61101 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason bad argument in call to erlang:size(nil) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-03-27 20:37:38.999 [error] <0.240.0> Supervisor {<0.240.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.5748>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.242.0>, {<<"client 127.0.0.1:61101 -> 127.0.0.1:5672">>,1}) at <0.243.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-27 20:37:38.999 [error] <0.227.0> Supervisor {<0.227.0>,'Elixir.Backbone.Supervisor'} had child 'Elixir.Backbone.Consumer' started with 'Elixir.Backbone.Consumer':start_link([], [{name,'Elixir.Backbone.Consumer'}]) at undefined exit with reason {shutdown,{gen_server,call,[<0.242.0>,{subscribe,{'basic.consume',0,nil,<<>>,false,false,false,false,[]},<0.244.0>},60000]}} in context start_error
2018-03-27 20:37:38.999 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Backbone.Consumer',{shutdown,{gen_server,call,[<0.242.0>,{subscribe,{'basic.consume',0,nil,<<>>,false,false,false,false,[]},<0.244.0>},60000]}}}},{'Elixir.Backbone.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-27 20:38:04.977 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2018-03-27 20:38:16.474 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
